import React from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Link } from "react-router-dom";
import { createPageUrl } from "../utils";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-stone-50 py-12 px-4">
      <div className="max-w-3xl mx-auto">
        <Link to={createPageUrl("Welcome")} className="text-emerald-600 hover:text-emerald-700 text-sm font-medium mb-8 inline-block">
          ← Back to Home
        </Link>

        <Card className="bg-white border-stone-200 shadow-sm">
          <CardContent className="p-8 md:p-12">
            <h1 className="text-4xl font-bold text-stone-900 mb-2">Terms of Service</h1>
            <p className="text-stone-600 mb-8">Last Updated: January 20, 2026</p>

            <div className="prose prose-stone max-w-none space-y-8">
              <section>
                <h2 className="text-2xl font-bold text-stone-900 mb-4">Overview</h2>
                <p className="text-stone-700 mb-4">
                  When you use Etsy Maker's Profit Pilot products or services, you are agreeing to these Terms of Service ("Terms"). Violation of these terms may, at our discretion, result in us terminating your account.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-stone-900 mb-4">Definitions</h2>
                <ul className="list-disc pl-6 space-y-2 text-stone-700">
                  <li>"Company", "we", "our", or "us" refers to Etsy Maker's Profit Pilot.</li>
                  <li>"Services" refers to our websites and any product created and maintained by Etsy Maker's Profit Pilot, including but not limited to our profit tracking, quote generation, order management, and production planning tools.</li>
                  <li>"You" or "your" refers to the people or organizations that own an account with one or more of our Services.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-stone-900 mb-4">Account Terms</h2>
                <ul className="list-disc pl-6 space-y-2 text-stone-700">
                  <li>You are responsible for maintaining the security of your account and password. The Company cannot and will not be liable for any loss or damage from your failure to comply with this security obligation.</li>
                  <li>You are responsible for all content posted to and activity that occurs under your account.</li>
                  <li>You must be a human. Accounts registered by "bots" or other automated methods are not permitted.</li>
                  <li>You are responsible for the accuracy of the financial data you input into the Services. The Company does not verify the accuracy of your data.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-stone-900 mb-4">Financial Data & Liability</h2>
                <ul className="list-disc pl-6 space-y-2 text-stone-700">
                  <li>
                    <strong>Data Accuracy:</strong> Etsy Maker's Profit Pilot is a tool for tracking and analyzing financial data. You acknowledge that calculations, reports, and recommendations generated by the Service are based on the data you provide. We are not liable for inaccurate results due to incorrect input data.
                  </li>
                  <li>
                    <strong>Tax & Legal Advice:</strong> The Services do not provide tax, accounting, or legal advice. You are solely responsible for consulting with qualified professionals regarding your business finances, tax obligations, and legal compliance. Results generated by the Service should not be used as a substitute for professional advice.
                  </li>
                  <li>
                    <strong>Etsy Integration:</strong> The Services may integrate with Etsy's platform. We are not affiliated with, endorsed by, or responsible for Etsy's services, data accuracy, or any changes Etsy makes to their fees or policies.
                  </li>
                  <li>
                    <strong>Third-Party Data:</strong> The Company is not liable for any inaccurate data provided by third-party services, including but not limited to payment processors, Etsy, or other integrated platforms.
                  </li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-stone-900 mb-4">User Content & Intellectual Property</h2>
                <ul className="list-disc pl-6 space-y-2 text-stone-700">
                  <li>You retain ownership of all business data, quotes, product information, and other content you create or upload to the Services.</li>
                  <li>By using the Services, you grant the Company a license to use, store, and process this data to provide the Services to you.</li>
                  <li>You agree not to upload or share content that is illegal, violates third-party rights, or infringes on intellectual property.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-stone-900 mb-4">Payment & Subscriptions</h2>
                <ul className="list-disc pl-6 space-y-2 text-stone-700">
                  <li>If you are using a free version of one of our Services, it is really free: we do not ask you for your credit card.</li>
                  <li>For paid Services, you need to pay in advance to keep using the Service. If you do not pay, we will freeze your account and it will be inaccessible until you make payment.</li>
                  <li>All fees are exclusive of all taxes, levies, or duties imposed by taxing authorities. You are responsible for payment of all such taxes, levies, or duties.</li>
                  <li>Refunds are processed at our sole discretion. Cancellations must be requested before the billing cycle renews.</li>
                  <li>We reserve the right to change pricing with 30 days' notice. Continued use of the Services after notice constitutes acceptance of new pricing.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-stone-900 mb-4">Cancellation & Termination</h2>
                <ul className="list-disc pl-6 space-y-2 text-stone-700">
                  <li>You are solely responsible for properly canceling your account. You can cancel your account at any time from your account settings.</li>
                  <li>Your data will be retained for a limited time after cancellation as required by law, then permanently deleted.</li>
                  <li>Performance of the Service may be terminated immediately if you abuse the Service (e.g., spamming, harassment, unauthorized access attempts).</li>
                  <li>We reserve the right to suspend or terminate your account and refuse any and all current or future use of our Services for any reason at any time.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-stone-900 mb-4">Data Privacy & Security</h2>
                <ul className="list-disc pl-6 space-y-2 text-stone-700">
                  <li>We use industry-standard security measures to protect your data. However, no system is 100% secure, and we cannot guarantee absolute security.</li>
                  <li>You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account.</li>
                  <li>We will notify you of any data breaches or security incidents as required by law.</li>
                  <li>For more details on how we handle your data, please review our Privacy Policy.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-stone-900 mb-4">Liability Limitation</h2>
                <p className="text-stone-700 mb-4">
                  You agree that the Company is not liable to you or to any third party for damages of any kind that result from:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-stone-700">
                  <li>The use of or inability to access the Services</li>
                  <li>Inaccurate financial calculations or reports</li>
                  <li>Unauthorized access to your data or account</li>
                  <li>Loss of business, revenue, or profits</li>
                  <li>Actions of any third party that uses the Services</li>
                  <li>Changes to Etsy's policies, fees, or platform</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-stone-900 mb-4">Intellectual Property</h2>
                <ul className="list-disc pl-6 space-y-2 text-stone-700">
                  <li>The Company or its licensors own all right, title, and interest in and to the Services, including all intellectual property rights therein.</li>
                  <li>You may not duplicate, copy, or reuse any portion of the code, design, or content of the Services without express written permission from the Company.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-stone-900 mb-4">Changes to Terms</h2>
                <p className="text-stone-700">
                  We may modify these Terms at any time. If we make material changes, we will notify you by email or by posting an updated version on the Services. Your continued use of the Services after such notification constitutes your acceptance of the modified Terms.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-stone-900 mb-4">Contact Us</h2>
                <p className="text-stone-700">
                  If you have questions about these Terms of Service, please contact us through your account settings or by reaching out to our support team.
                </p>
              </section>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}